micronaut:
  application:
    name: app-netty
---
micronaut:
  router:
    static-resources:
      assets:
        paths: 'classpath:assets'
        mapping: '/assets/**'
---
micronaut:
  security:
    endpoints:
      logout:
        get-allowed: true
    authentication: idtoken
    redirect:
      forbidden:
        url: '/forbidden'
      unauthorized:
        url: '/oauth/login/cognito'
    intercept-url-map:
      -
        http-method: GET
        pattern: '/microstream/root'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/*/root'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/dictionary'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/*/dictionary'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/object/*'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/*/object/*'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/maintenance/filesStatistics'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/microstream/*/maintenance/filesStatistics'
        access:
          - 'isAnonymous()'
      -
        http-method: GET
        pattern: '/assets/javascripts/controllers/*'
        access:
          - 'isAnonymous()'
websockets:
  url: 'localhost:8080/todo'
---
microstream:
  rest:
    enabled: true
  storage:
    todos:
      root-class: 'com.micronauttodo.repositories.microstream.RootData'
      storage-directory: '/Users/sdelamo/todos'
---
endpoints:
  health:
    details-visible: anonymous
