micronaut:
  security:
    redirect:
      forbidden:
        url: '/forbidden'
      unauthorized:
        url: '/oauth/login/cognito'
    authentication: idtoken
    endpoints:
      logout:
        get-allowed: true
